# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recorders.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recordersDialog(object):
    def setupUi(self, recordersDialog):
        recordersDialog.setObjectName("recordersDialog")
        recordersDialog.resize(758, 268)
        self.gridLayout_2 = QtWidgets.QGridLayout(recordersDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addRecorderLayout = QtWidgets.QGridLayout()
        self.addRecorderLayout.setObjectName("addRecorderLayout")
        self.nameLabel = QtWidgets.QLabel(recordersDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.addRecorderLayout.addWidget(self.nameLabel, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(recordersDialog)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.addRecorderLayout.addWidget(self.checkBox, 4, 1, 1, 1)
        self.targetConfigLayout = QtWidgets.QGridLayout()
        self.targetConfigLayout.setObjectName("targetConfigLayout")
        self.gyroLabel = QtWidgets.QLabel(recordersDialog)
        self.gyroLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gyroLabel.setObjectName("gyroLabel")
        self.targetConfigLayout.addWidget(self.gyroLabel, 0, 3, 1, 1)
        self.targetBatchSizeLabel = QtWidgets.QLabel(recordersDialog)
        self.targetBatchSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.targetBatchSizeLabel.setObjectName("targetBatchSizeLabel")
        self.targetConfigLayout.addWidget(self.targetBatchSizeLabel, 0, 1, 1, 1)
        self.accelerometerLabel = QtWidgets.QLabel(recordersDialog)
        self.accelerometerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.accelerometerLabel.setObjectName("accelerometerLabel")
        self.targetConfigLayout.addWidget(self.accelerometerLabel, 0, 2, 1, 1)
        self.targetSampleRate = QtWidgets.QSpinBox(recordersDialog)
        self.targetSampleRate.setMinimum(100)
        self.targetSampleRate.setMaximum(1000)
        self.targetSampleRate.setProperty("value", 500)
        self.targetSampleRate.setObjectName("targetSampleRate")
        self.targetConfigLayout.addWidget(self.targetSampleRate, 1, 0, 1, 1)
        self.targetBatchSize = QtWidgets.QSpinBox(recordersDialog)
        self.targetBatchSize.setMinimum(1)
        self.targetBatchSize.setMaximum(100)
        self.targetBatchSize.setProperty("value", 50)
        self.targetBatchSize.setObjectName("targetBatchSize")
        self.targetConfigLayout.addWidget(self.targetBatchSize, 1, 1, 1, 1)
        self.targetAccelerometerLayout = QtWidgets.QHBoxLayout()
        self.targetAccelerometerLayout.setObjectName("targetAccelerometerLayout")
        self.targetAccelEnabled = QtWidgets.QCheckBox(recordersDialog)
        self.targetAccelEnabled.setChecked(True)
        self.targetAccelEnabled.setObjectName("targetAccelEnabled")
        self.targetAccelerometerLayout.addWidget(self.targetAccelEnabled)
        self.targetAccelSens = QtWidgets.QComboBox(recordersDialog)
        self.targetAccelSens.setObjectName("targetAccelSens")
        self.targetAccelSens.addItem("")
        self.targetAccelSens.addItem("")
        self.targetAccelSens.addItem("")
        self.targetAccelSens.addItem("")
        self.targetAccelerometerLayout.addWidget(self.targetAccelSens)
        self.targetConfigLayout.addLayout(self.targetAccelerometerLayout, 1, 2, 1, 1)
        self.targetGyroLayout = QtWidgets.QHBoxLayout()
        self.targetGyroLayout.setObjectName("targetGyroLayout")
        self.targetGyroEnabled = QtWidgets.QCheckBox(recordersDialog)
        self.targetGyroEnabled.setObjectName("targetGyroEnabled")
        self.targetGyroLayout.addWidget(self.targetGyroEnabled)
        self.targetGyroSens = QtWidgets.QComboBox(recordersDialog)
        self.targetGyroSens.setObjectName("targetGyroSens")
        self.targetGyroSens.addItem("")
        self.targetGyroSens.addItem("")
        self.targetGyroSens.addItem("")
        self.targetGyroSens.addItem("")
        self.targetGyroLayout.addWidget(self.targetGyroSens)
        self.targetConfigLayout.addLayout(self.targetGyroLayout, 1, 3, 1, 1)
        self.targetSampleRateLabel = QtWidgets.QLabel(recordersDialog)
        self.targetSampleRateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.targetSampleRateLabel.setObjectName("targetSampleRateLabel")
        self.targetConfigLayout.addWidget(self.targetSampleRateLabel, 0, 0, 1, 1)
        self.applyTargetButton = QtWidgets.QToolButton(recordersDialog)
        self.applyTargetButton.setObjectName("applyTargetButton")
        self.targetConfigLayout.addWidget(self.applyTargetButton, 0, 4, 1, 1)
        self.resetTargetButton = QtWidgets.QToolButton(recordersDialog)
        self.resetTargetButton.setObjectName("resetTargetButton")
        self.targetConfigLayout.addWidget(self.resetTargetButton, 1, 4, 1, 1)
        self.addRecorderLayout.addLayout(self.targetConfigLayout, 1, 0, 1, 7)
        self.ipAddressLabel = QtWidgets.QLabel(recordersDialog)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.addRecorderLayout.addWidget(self.ipAddressLabel, 3, 2, 1, 1)
        self.name = QtWidgets.QLineEdit(recordersDialog)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.addRecorderLayout.addWidget(self.name, 3, 1, 1, 1)
        self.configHeaderLabel = QtWidgets.QLabel(recordersDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.configHeaderLabel.setFont(font)
        self.configHeaderLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.configHeaderLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.configHeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.configHeaderLabel.setObjectName("configHeaderLabel")
        self.addRecorderLayout.addWidget(self.configHeaderLabel, 0, 0, 1, 7)
        self.recorderSampleIndex = QtWidgets.QSpinBox(recordersDialog)
        self.recorderSampleIndex.setMaximum(999999999)
        self.recorderSampleIndex.setObjectName("recorderSampleIndex")
        self.addRecorderLayout.addWidget(self.recorderSampleIndex, 3, 5, 1, 1)
        self.disconnectRecorderButton = QtWidgets.QToolButton(recordersDialog)
        self.disconnectRecorderButton.setObjectName("disconnectRecorderButton")
        self.addRecorderLayout.addWidget(self.disconnectRecorderButton, 4, 6, 1, 1)
        self.recordersHeaderLabel = QtWidgets.QLabel(recordersDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.recordersHeaderLabel.setFont(font)
        self.recordersHeaderLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.recordersHeaderLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.recordersHeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recordersHeaderLabel.setObjectName("recordersHeaderLabel")
        self.addRecorderLayout.addWidget(self.recordersHeaderLabel, 2, 0, 1, 7)
        self.connectRecorderButton = QtWidgets.QToolButton(recordersDialog)
        self.connectRecorderButton.setObjectName("connectRecorderButton")
        self.addRecorderLayout.addWidget(self.connectRecorderButton, 3, 6, 1, 1)
        self.statusLabel = QtWidgets.QLabel(recordersDialog)
        self.statusLabel.setObjectName("statusLabel")
        self.addRecorderLayout.addWidget(self.statusLabel, 4, 0, 1, 1)
        self.statusText = QtWidgets.QLineEdit(recordersDialog)
        self.statusText.setReadOnly(True)
        self.statusText.setObjectName("statusText")
        self.addRecorderLayout.addWidget(self.statusText, 4, 2, 1, 4)
        self.ipAddress = QtWidgets.QLineEdit(recordersDialog)
        self.ipAddress.setObjectName("ipAddress")
        self.addRecorderLayout.addWidget(self.ipAddress, 3, 3, 1, 1)
        self.port = QtWidgets.QSpinBox(recordersDialog)
        self.port.setMinimum(8000)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 10002)
        self.port.setObjectName("port")
        self.addRecorderLayout.addWidget(self.port, 3, 4, 1, 1)
        self.gridLayout_2.addLayout(self.addRecorderLayout, 0, 0, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addRecorderButton = QtWidgets.QPushButton(recordersDialog)
        self.addRecorderButton.setObjectName("addRecorderButton")
        self.buttonLayout.addWidget(self.addRecorderButton)
        self.saveRecordersButton = QtWidgets.QPushButton(recordersDialog)
        self.saveRecordersButton.setObjectName("saveRecordersButton")
        self.buttonLayout.addWidget(self.saveRecordersButton)
        self.gridLayout_2.addLayout(self.buttonLayout, 2, 0, 1, 1)

        self.retranslateUi(recordersDialog)
        self.resetTargetButton.clicked.connect(recordersDialog.reset_target)
        self.applyTargetButton.clicked.connect(recordersDialog.apply_target)
        self.targetSampleRate.valueChanged['int'].connect(recordersDialog.update_target)
        self.targetBatchSize.valueChanged['int'].connect(recordersDialog.update_target)
        self.targetAccelEnabled.stateChanged['int'].connect(recordersDialog.update_target)
        self.targetAccelSens.currentIndexChanged['int'].connect(recordersDialog.update_target)
        self.targetGyroEnabled.stateChanged['int'].connect(recordersDialog.update_target)
        self.targetGyroSens.currentIndexChanged['int'].connect(recordersDialog.update_target)
        self.connectRecorderButton.clicked.connect(recordersDialog.connect_recorder)
        self.disconnectRecorderButton.clicked.connect(recordersDialog.disconnect_recorder)
        self.saveRecordersButton.clicked.connect(recordersDialog.save_recorders)
        self.addRecorderButton.clicked.connect(recordersDialog.add_new_recorder)
        QtCore.QMetaObject.connectSlotsByName(recordersDialog)

    def retranslateUi(self, recordersDialog):
        _translate = QtCore.QCoreApplication.translate
        recordersDialog.setWindowTitle(_translate("recordersDialog", "Recorders"))
        self.nameLabel.setText(_translate("recordersDialog", "Name"))
        self.checkBox.setText(_translate("recordersDialog", "OK?"))
        self.gyroLabel.setText(_translate("recordersDialog", "Gyro"))
        self.targetBatchSizeLabel.setText(_translate("recordersDialog", "Batch Size"))
        self.accelerometerLabel.setText(_translate("recordersDialog", "Accelerometer"))
        self.targetSampleRate.setSuffix(_translate("recordersDialog", " Hz"))
        self.targetAccelEnabled.setText(_translate("recordersDialog", "Enabled?"))
        self.targetAccelSens.setItemText(0, _translate("recordersDialog", "2"))
        self.targetAccelSens.setItemText(1, _translate("recordersDialog", "4"))
        self.targetAccelSens.setItemText(2, _translate("recordersDialog", "8"))
        self.targetAccelSens.setItemText(3, _translate("recordersDialog", "16"))
        self.targetGyroEnabled.setText(_translate("recordersDialog", "Enabled?"))
        self.targetGyroSens.setItemText(0, _translate("recordersDialog", "250"))
        self.targetGyroSens.setItemText(1, _translate("recordersDialog", "500"))
        self.targetGyroSens.setItemText(2, _translate("recordersDialog", "1000"))
        self.targetGyroSens.setItemText(3, _translate("recordersDialog", "2000"))
        self.targetSampleRateLabel.setText(_translate("recordersDialog", "Sample Rate"))
        self.applyTargetButton.setText(_translate("recordersDialog", "..."))
        self.resetTargetButton.setText(_translate("recordersDialog", "..."))
        self.ipAddressLabel.setText(_translate("recordersDialog", "IP Address"))
        self.configHeaderLabel.setText(_translate("recordersDialog", "Configuration"))
        self.disconnectRecorderButton.setText(_translate("recordersDialog", "..."))
        self.recordersHeaderLabel.setText(_translate("recordersDialog", "Recorders"))
        self.connectRecorderButton.setText(_translate("recordersDialog", "..."))
        self.statusLabel.setText(_translate("recordersDialog", "Status"))
        self.ipAddress.setInputMask(_translate("recordersDialog", "000.000.000.000;_"))
        self.addRecorderButton.setText(_translate("recordersDialog", "Add New Recorder"))
        self.saveRecordersButton.setText(_translate("recordersDialog", "Save Recorders"))
