# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'savewav.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveWavDialog(object):
    def setupUi(self, saveWavDialog):
        saveWavDialog.setObjectName("saveWavDialog")
        saveWavDialog.resize(393, 252)
        self.gridLayout = QtWidgets.QGridLayout(saveWavDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(saveWavDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 3)
        self.fileNameLabel = QtWidgets.QLabel(saveWavDialog)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.gridLayout.addWidget(self.fileNameLabel, 4, 0, 1, 1)
        self.measurementLabel = QtWidgets.QLabel(saveWavDialog)
        self.measurementLabel.setObjectName("measurementLabel")
        self.gridLayout.addWidget(self.measurementLabel, 0, 0, 1, 1)
        self.location = QtWidgets.QLineEdit(saveWavDialog)
        self.location.setReadOnly(True)
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 3, 1, 1, 1)
        self.axesLabel = QtWidgets.QLabel(saveWavDialog)
        self.axesLabel.setObjectName("axesLabel")
        self.gridLayout.addWidget(self.axesLabel, 1, 0, 1, 1)
        self.axes = QtWidgets.QListWidget(saveWavDialog)
        self.axes.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.axes.setObjectName("axes")
        item = QtWidgets.QListWidgetItem()
        self.axes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.axes.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.axes.addItem(item)
        self.gridLayout.addWidget(self.axes, 1, 1, 1, 2)
        self.locationPicker = QtWidgets.QToolButton(saveWavDialog)
        self.locationPicker.setObjectName("locationPicker")
        self.gridLayout.addWidget(self.locationPicker, 3, 2, 1, 1)
        self.fileName = QtWidgets.QLineEdit(saveWavDialog)
        self.fileName.setObjectName("fileName")
        self.gridLayout.addWidget(self.fileName, 4, 1, 1, 2)
        self.measurement = QtWidgets.QComboBox(saveWavDialog)
        self.measurement.setObjectName("measurement")
        self.gridLayout.addWidget(self.measurement, 0, 1, 1, 2)
        self.locationLabel = QtWidgets.QLabel(saveWavDialog)
        self.locationLabel.setObjectName("locationLabel")
        self.gridLayout.addWidget(self.locationLabel, 3, 0, 1, 1)
        self.outputFsLabel = QtWidgets.QLabel(saveWavDialog)
        self.outputFsLabel.setObjectName("outputFsLabel")
        self.gridLayout.addWidget(self.outputFsLabel, 2, 0, 1, 1)
        self.outputFs = QtWidgets.QComboBox(saveWavDialog)
        self.outputFs.setObjectName("outputFs")
        self.outputFs.addItem("")
        self.outputFs.addItem("")
        self.outputFs.addItem("")
        self.gridLayout.addWidget(self.outputFs, 2, 1, 1, 2)

        self.retranslateUi(saveWavDialog)
        self.buttonBox.accepted.connect(saveWavDialog.accept)
        self.buttonBox.rejected.connect(saveWavDialog.reject)
        self.locationPicker.clicked.connect(saveWavDialog.select_location)
        self.fileName.textChanged['QString'].connect(saveWavDialog.validate_name)
        QtCore.QMetaObject.connectSlotsByName(saveWavDialog)

    def retranslateUi(self, saveWavDialog):
        _translate = QtCore.QCoreApplication.translate
        saveWavDialog.setWindowTitle(_translate("saveWavDialog", "Dialog"))
        self.fileNameLabel.setText(_translate("saveWavDialog", "Name"))
        self.measurementLabel.setText(_translate("saveWavDialog", "Measurement"))
        self.axesLabel.setText(_translate("saveWavDialog", "Axes"))
        __sortingEnabled = self.axes.isSortingEnabled()
        self.axes.setSortingEnabled(False)
        item = self.axes.item(0)
        item.setText(_translate("saveWavDialog", "x"))
        item = self.axes.item(1)
        item.setText(_translate("saveWavDialog", "y"))
        item = self.axes.item(2)
        item.setText(_translate("saveWavDialog", "z"))
        self.axes.setSortingEnabled(__sortingEnabled)
        self.locationPicker.setText(_translate("saveWavDialog", "..."))
        self.locationLabel.setText(_translate("saveWavDialog", "Location"))
        self.outputFsLabel.setText(_translate("saveWavDialog", "Output Fs"))
        self.outputFs.setItemText(0, _translate("saveWavDialog", "Native"))
        self.outputFs.setItemText(1, _translate("saveWavDialog", "44.1 kHz"))
        self.outputFs.setItemText(2, _translate("saveWavDialog", "48 kHz"))
